// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  angular.module('app').controller('EditCtrl', [
    '$scope', '$http', '$routeParams', 'curx', function($scope, $http, $routeParams, curx) {
      $scope.getExercises = function() {
        if (localStorage['clis'] !== void 0) {
          return $scope.subjects = JSON.parse(localStorage['clis']);
        } else {
          return $http.get('/clis.json').success(function(data) {});
        }
      };
      $scope.setCur = function(x) {
        return $scope.curX = x;
      };
      $scope.val = function(it) {
        return new RegExp('^' + it.check + '$').test(it.sample);
      };
      $scope.create = function() {
        $scope.subjects[$scope.exercise.subject][$scope.exercise.module].push($scope.exercise);
        $scope.updateLocalStorage();
        return alert('created');
      };
      $('#single_clippy').clippy({
        text: localStorage['clis']
      });
      $scope.remove = function(module, idx) {
        $scope.subjects[$scope.asubj][module].splice(idx, 1);
        return $scope.updateLocalStorage();
      };
      $scope.change = function() {};
      $scope.updateLocalStorage = function() {
        localStorage['clis'] = JSON.stringify($scope.subjects);
        return $('#single_clippy').clippy({
          text: localStorage['clis']
        });
      };
      return $scope.resetExercises = function() {
        return $http.get('/clis.json').success(function(data) {
          $scope.subjects = data;
          return localStorage['clis'] = JSON.stringify($scope.subjects);
        });
      };
    }
  ]);

}).call(this);
