// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('app').directive('ngDrag', function() {
    return function(scope, element, attrs) {
      element.css('cursor', 'crosshair');
      return element.bind('dragstart', function(event) {
        return scope.$apply(scope.$eval(attrs.ngDrag));
      });
    };
  }).directive('ngDrop', function() {
    return function(scope, element, attrs) {
      element.bind('drop', function(event) {
        event.preventDefault();
        scope.$apply(scope.$eval(attrs.ngDrop));
        return element.css('border-top', '1px solid #ddd');
      });
      element.bind('dragenter dragover', function(event) {
        event.preventDefault();
        return element.css('border-top', '2px solid #ddd');
      });
      return element.bind('dragleave', function(event) {
        event.preventDefault();
        return element.css('border-top', '1px solid #ddd');
      });
    };
  });

}).call(this);
